# Site
repository: shanujshekhar/shanujshekhar.github.io
favicon: images/favicon.ico

# Personal info
name: Shanuj Shekhar
title: Stony Brook Graduate Student
email: shanuj.shekhar@stonybrook.edu
website: https://shanujshekhar.github.io
resume: https://shanujshekhar.github.io/Shanuj_Shekhar_CV.pdf

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  shanujshekhar
# dribbble_username:
# facebook_username:
# flickr_username:
instagram_username: shanuj9708
linkedin_username: shanujshekhar
# pinterest_username:
# youtube_username:
# googleplus_username:

# About Section
# about_title: About Me
about_profile_image: images/jg.jpg
about_content: |
  Hi, my name is Shanuj Shekhar and I currently pursuing Masters Degree in Computer Science from Stony Brook University. I am fron India and I have completed my undergrad studies in my home country.  

# More Section
more_title: Skills
more_content: |
  <style>
    .skills{
      list-style: none;
      padding: 0;
      width: 400px;
      color: white;
    }
    .skills li{
      margin: 20px 0;
    }
    .bar{
      background: #353b48;
      display: block;
      height: 10px;
      border: 1px solid rgba(0,0,0,0.3);
      border-radius: 3px;
      overflow: hidden;
      box-shadow: 0 0 10px #2187e7b3;
    }
    .bar span{
      height: 10px;
      float: left;
      background: #e6e6e6;
    }
    
    .java{
      width: 90%;
      animation: java 2s;
    }
    .python{
      width: 80%;
      animation: python 2s;
    }
    .cplus{
      width: 70%;
      animation: cplus 2s;
    }
    .c{
      width: 40%;
      animation: c 2s;
    }
    
    @keyframes java{
      0%{
        width: 0%;
      }
      100%{
        width: 90%;
      }
    }
    @keyframes python{
      0%{
        width: 0%;
      }
      100%{
        width: 80%;
      }
    }
    @keyframes cplus{
      0%{
        width: 0%;
      }
      100%{
        width: 70%;
      }
    }
    @keyframes c{
      0%{
        width: 0%;
      }
      100%{
        width: 40%;
      }
    }
    </style>
  
  <div class="skills">
    <li>
      <p>Java</p><span class="bar"><span class="java"></span></span>
    </li>
    <li>
      <p>Python</p><span class="bar"><span class="python"></span></span>
    </li>
    <li>
      <p>C++</p><span class="bar"><span class="cplus"></span></span>
    </li>
    <li>
      <p>C</p><span class="bar"><span class="c"></span></span>
    </li>
  </div>


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education


# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
