# Site
repository: shanujshekhar/shanujshekhar.github.io
favicon: images/favicon.ico

# Personal info
name: Shanuj Shekhar
title: Stony Brook Graduate Student
email: shanuj.shekhar@stonybrook.edu
website: https://shanujshekhar.github.io
resume: https://shanujshekhar.github.io/Shanuj_Shekhar_CV.pdf

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  shanujshekhar
# dribbble_username:
# facebook_username:
# flickr_username:
instagram_username: shanuj9708
linkedin_username: shanujshekhar
# pinterest_username:
# youtube_username:
# googleplus_username:

# About Section
# about_title: About Me
about_profile_image: images/jg.jpg
about_content: |
  Hi, my name is Shanuj Shekhar and I currently pursuing Masters Degree in Computer Science from Stony Brook University. I am fron India and I have completed my undergrad studies in my home country.  

# More Section
more_title: Skills
more_content: |
  <style>
    .skills{
      list-style: none;
      padding: 0;
      width: 100%;
      color: white;
    }
    .skills li{
      margin: 20px 0;
    }
    .bar{
      background: #353b48;
      display: block;
      height: 15px;
      border: 1px solid rgba(0,0,0,0.3);
      border-radius: 3px;
      overflow: hidden;
      box-shadow: 0 0 10px #2187e7b3;
    }
    .bar span{
      height: 15px;
      float: left;
      background: #e6e6e6;
    }
    
    .java{
      width: 90%;
      animation: java 2s;
    }
    @keyframes java{
      0%{
        width: 0%;
      }
      100%{
        width: 90%;
      }
    }
    
    .python{
      width: 85%;
      animation: python 2s;
    }
    @keyframes python{
      0%{
        width: 0%;
      }
      100%{
        width: 85%;
      }
    }
    
    .csharp{
      width: 45%;
      animation: csharp 2s;
    }
    @keyframes csharp{
      0%{
        width: 0%;
      }
      100%{
        width: 45%;
      }
    }
    
    .cplus{
      width: 70%;
      animation: cplus 2s;
    }
    @keyframes cplus{
      0%{
        width: 0%;
      }
      100%{
        width: 70%;
      }
    }
    
    .c{
      width: 40%;
      animation: c 2s;
    }
    @keyframes c{
      0%{
        width: 0%;
      }
      100%{
        width: 40%;
      }
    }
    
    .front_end{
      width: 85%;
      animation: front_end 2s;
    }
    @keyframes front_end{
      0%{
        width: 0%;
      }
      100%{
        width: 85%;
      }
    }
    
    /* Create two equal columns that floats next to each other */
    .column {
      float: left;
      width: 50%;
      padding: 10px;
      height: 300px; /* Should be removed. Only for demonstration */
    }

    /* Clear floats after the columns */
    .skills:after {
      content: "";
      display: table;
      clear: both;
    }

    /* Responsive layout - makes the two columns stack on top of each other instead of next to each other */
    @media screen and (max-width: 600px) {
      .column {
        width: 100%;
      }
    </style>
  
  <div class="skills">
    <div class="column">
      <li>
        <p>Java</p><div style="float:right;">90%</div><span class="bar"><span class="java"></span></span>
      </li>
      <li>
        <p>Python</p><div style="float:right;">85%</div><span class="bar"><span class="python"></span></span>
      </li>
      <li>
        <p>C#</p><div style="float:right;">45%</div><span class="bar"><span class="csharp"></span></span>
      </li>
    </div>
    <div class="column">
      <li>
        <p>HTML/CSS/Javascript</p><div style="float:right;">85%</div><span class="bar"><span class="front_end"></span></span>
      </li>
      <li>
        <p>C++</p><div style="float:right;">70%</div><span class="bar"><span class="cplus"></span></span>
      </li>
      <li>
        <p>C</p><div style="float:right;">40%</div><span class="bar"><span class="c"></span></span>
      </li>
    </div>
  </div>



# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education


# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
